language: csharp
solution: TodList.sln

jobs:
  dotnet: 2.2.108
  script: 
    - dotnet restore 
    - dotnet build --configuration Release
    - dotnet test

services:
  - docker
before_install:
  - docker-compose build