version: '3'

services:
  todolist:
    image: todolist
    build:
      context: .
      dockerfile: src/TodoList.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5106:80" # the aspnetcore container sets 80 as the default port
